USE [master]
GO

/****** Object:  Database [agencia_de_viagem]    Script Date: 12/11/2022 21:19:08 ******/
CREATE DATABASE [agencia_de_viagem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'agencia_de_viagem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\agencia_de_viagem.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'agencia_de_viagem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\agencia_de_viagem_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [agencia_de_viagem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [agencia_de_viagem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [agencia_de_viagem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [agencia_de_viagem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [agencia_de_viagem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [agencia_de_viagem] SET ARITHABORT OFF 
GO

ALTER DATABASE [agencia_de_viagem] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [agencia_de_viagem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [agencia_de_viagem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [agencia_de_viagem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [agencia_de_viagem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [agencia_de_viagem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [agencia_de_viagem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [agencia_de_viagem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [agencia_de_viagem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [agencia_de_viagem] SET  ENABLE_BROKER 
GO

ALTER DATABASE [agencia_de_viagem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [agencia_de_viagem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [agencia_de_viagem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [agencia_de_viagem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [agencia_de_viagem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [agencia_de_viagem] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [agencia_de_viagem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [agencia_de_viagem] SET RECOVERY FULL 
GO

ALTER DATABASE [agencia_de_viagem] SET  MULTI_USER 
GO

ALTER DATABASE [agencia_de_viagem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [agencia_de_viagem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [agencia_de_viagem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [agencia_de_viagem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [agencia_de_viagem] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [agencia_de_viagem] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [agencia_de_viagem] SET QUERY_STORE = OFF
GO

ALTER DATABASE [agencia_de_viagem] SET  READ_WRITE 
GO

